language: python
python:
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libevent-dev lzop pv gnupg
  - sudo rm /usr/share/google/boto/boto_plugins/*
install: pip install -q tox
script: tox
notifications:
  email: false
